FROM nvcr.io/nvidia/pytorch:23.10-py3

ENV http_proxy=http://137.153.170.55:10080/ \
    https_proxy=http://137.153.170.55:10080/ \
    HTTP_PROXY=http://137.153.170.55:10080/ \
    HTTPS_PROXY=http://137.153.170.55:10080/
    
ENV DEBIAN_FRONTEND=noninteractive


# Update GPG key of NVIDIA Docker Images 
# (See https://developer.nvidia.com/blog/updating-the-cuda-linux-gpg-repository-key/ for more detail)
RUN rm -f /etc/apt/sources.list.d/cuda.list \
 && apt-get update && apt-get install -y --no-install-recommends \
    wget \
 && wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-keyring_1.0-1_all.deb \
 && dpkg -i cuda-keyring_1.0-1_all.deb \
 && rm -f cuda-keyring_1.0-1_all.deb

RUN apt-get clean && apt-get update && \
    apt-get install -y --no-install-recommends --fix-missing \
    nano curl git zip htop unzip tmux ca-certificates sudo bzip2 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
    apt-get install -y --no-install-recommends --fix-missing \
    build-essential vim gcc g++ make openssl ffmpeg \
    && apt-get clean && rm -rf /var/lib/apt/lists/*


RUN apt update && apt install -y --no-install-recommends apt-transport-https gnupg && \
    curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg && \
    mv bazel-archive-keyring.gpg /usr/share/keyrings && \
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" > /etc/apt/sources.list.d/bazel.list && \
    apt update && apt install -y --no-install-recommends bazel-5.3.2 && \
    ln -sf /usr/bin/bazel-5.3.2 /usr/bin/bazel \
    && apt-get clean \ 
    && rm -rf /var/lib/apt/lists/*

RUN python -m pip install --upgrade pip
RUN pip install alias-free-torch==0.0.6 auraloss==0.4.0 descript-audio-codec descript-audiotools einops einops-exts==0.0.4 ema-pytorch==0.2.3
RUN pip install gradio huggingface_hub importlib-resources==5.12.0 mpi4py opencv-python timm==0.9.12 gdown networkx
RUN pip install pandas==2.0.2 pedalboard==0.7.4 prefigure==0.0.9 pytorch_lightning PyWavelets safetensors omegaconf moviepy annoy matplotlib
RUN pip install sentencepiece==0.1.99 s3fs torchmetrics==0.11.4 tqdm nitrous-ema fvcore iopath submitit scikit-image h5py
RUN pip install wandb==0.15.4 webdataset==0.2.48 x-transformers diffusers ninja av ffmpeg-python yt-dlp seaborn prettytable hdf5plugin
RUN pip install scikit_learn==1.0.2 soundfile==0.11.0 termcolor==2.1.0 hydra-colorlog hydra-core openpyxl==3.1.2
RUN pip install pytest==7.4.3 pylint==3.0.2 pyloudnorm==0.1.1 pandarallel==1.6.5 julius==0.2.7 mutagen==1.47.0 GitPython==3.1.40 boto3==1.34.60 rich==13.7.1 dictdiffer==0.9.0 torchopenl3==1.0.1
RUN pip install laion-clap python-dotenv tensordict==0.6.0 deepspeed accelerate fastapi uvicorn aiortc asyncio pillow
RUN pip install librosa scipy==1.11.1
RUN pip install numpy==1.26.4 
RUN pip uninstall torch -y
RUN pip install --extra-index-url https://download.pytorch.org/whl/cu121 \
    torch==2.5.1+cu121 torchvision==0.20.1+cu121 torchaudio==2.5.1+cu121
# RUN pip install xformers==0.0.29 
RUN pip install passt@git+https://github.com/hkchengrex/passt_hear21.git
RUN pip uninstall -y transformer-engine
RUN pip uninstall -y apex
